### ISSUE TITLE
yvm failed to install

### ISSUE THREAD

**Issue by bananaAmbon** [tophat/yvm#325] opened 2019-03-14 09:01 UTC
**Describe the bug**
failed to install yvm.

**To Reproduce**
1. curl -fsSL https://raw.githubusercontent.com/tophat/yvm/master/scripts/install.sh | bash

**Screenshots**
![yvm_failed](https://user-images.githubusercontent.com/41948189/54343809-2dcaeb00-4672-11e9-9c61-363c603b5f45.PNG)

**Desktop:**
 - OS: WIndows 10
 - YVM Version: -
 - Shell: bash
 - Node version: 11.11.0

**Comment by mcataford** [comment] 2019-03-14 14:48
I can get a Windows machine sometime today to test it out, but my first guess is that your Linux Subsystem doesn't have `unzip` installed. 

I haven't dealt with Windows 10's bash in a while, but could you check if `unzip` is installed (via `apt list unzip`)? This should confirm whether it's a missing dependency problem (in which case you should be able to get through by installing `unzip`) or whether the issue is somewhere else.

In the meantime, I'll try to reproduce when I get a hand on my Windows machine.

**Comment by mcataford** [comment] 2019-03-15 00:44
@bananaAmbon I ran the scenario on my W10 machine with the Linux subsystem and can confirm, it's a dependency issue.

I was able to reproduce what you saw by trying to install `yvm` with W10 bash out-of-the-box, but it installed fine after installed `unzip`.

Try out `sudo apt-get install unzip` and then retry installing using the line you posted earlier, that should allow you go proceed through!

**Comment by bananaAmbon** [comment] 2019-03-15 17:59
@mcataford thanks man, its work. but is it only installed in my subsystem?

Any hint to use in my windows machine?

**Comment by iamogbz** [comment] 2019-03-17 04:44
@bananaAmbon installing [`unzip`](https://www.mkssoftware.com/docs/man1/unzip.1.asp) for windows would be the best option as it allows yvm to self update. However the manual installation will also work https://github.com/tophat/yvm#manual-installation

**Comment by mcataford** [comment] 2019-03-17 13:54
@bananaAmbon To built on what @iamogbz said (and regarding your first point): packages you install through the Win10 Linux subsystem are limited to the subsystem. If you install it outside of the provided Bash shell, those will be two separate instances and changes on one won't affect the other.

**Comment by mcataford** [comment] 2019-03-20 20:25
@bananaAmbon I think that we circled the issue pretty well in previous discussion, I'm going to close this issue.

Thanks for reporting the difficulties you were having! I'm glad you were able to install `yvm` after all! Don't hesitate to reach out if there's anything else that pops up, related to this issue or not.

**Closed by mcataford** 2019-03-20 20:25 UTC
